### ISSUE TITLE
Boolean attributes

### ISSUE THREAD

**Issue by doekman** [stefanhaustein/notemplate#2]
Did you consider boolean attributes, for attributes like `disabled` and `readonly`? 

Like this:

    element("input", {disabled: age<18})

The disabled attribute is only set when the value is true. Both key and value are the same.

**Comment by stefanhaustein** [comment]
Seems like a good fit. What would be the value though? Just repeat the attribute name?

**Comment by doekman** [comment]
Some people do that, but [MDC's entry on setAttribute](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute) mentions using an empty string for the value.

**Comment by stefanhaustein** [comment]
Sounds good, do you want to send a PR? O:)

**Comment by doekman** [comment]
Yep! Really like this library; thanks.

**Comment by stefanhaustein** [comment]
Thanks a lot! I am using an Apple keyboard and it keeps inserting non-breaking spaces (until I get fed up and fix it in the keyboard settings, which seem to be somewhere else in each new linux version I am using)

**Comment by doekman** [comment]
TIL: "The keyboard shortcut for inserting a non-breaking space is Option–Space."
